"""add admin users

Revision ID: 1df3125452f9
Revises: ec08acde2a6a
Create Date: 2026-04-13 00:41:23.530659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1df3125452f9'
down_revision: Union[str, Sequence[str], None] = 'ec08acde2a6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('api_token', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'TENANT_ADMIN', name='roleenum'), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_api_token'), 'admin_users', ['api_token'], unique=True)
    op.create_index(op.f('ix_admin_users_id'), 'admin_users', ['id'], unique=False)
    op.create_index(op.f('ix_admin_users_username'), 'admin_users', ['username'], unique=True)
    op.create_unique_constraint('uix_attendance_record', 'attendance_logs', ['tenant_id', 'device_id', 'finger_id', 'timestamp'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_attendance_record', 'attendance_logs', type_='unique')
    op.drop_index(op.f('ix_admin_users_username'), table_name='admin_users')
    op.drop_index(op.f('ix_admin_users_id'), table_name='admin_users')
    op.drop_index(op.f('ix_admin_users_api_token'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
