"""add employee_code fix

Revision ID: 3486e68d0e91
Revises: 90405d9757e0
Create Date: 2026-04-16 02:29:04.754149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3486e68d0e91'
down_revision: Union[str, Sequence[str], None] = '90405d9757e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employees')
    op.drop_table('settings')
    op.drop_table('leaves')
    op.drop_table('holidays')
    op.drop_table('departments')
    op.drop_table('notifications')
    op.alter_column('admin_users', 'username',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('admin_users', 'password',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('admin_users', 'api_token',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.drop_constraint(op.f('admin_users_api_token_key'), 'admin_users', type_='unique')
    op.drop_constraint(op.f('admin_users_username_key'), 'admin_users', type_='unique')
    op.create_index(op.f('ix_admin_users_api_token'), 'admin_users', ['api_token'], unique=True)
    op.create_index(op.f('ix_admin_users_id'), 'admin_users', ['id'], unique=False)
    op.create_index(op.f('ix_admin_users_username'), 'admin_users', ['username'], unique=True)
    op.alter_column('attendance_logs', 'device_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('attendance_logs', 'record_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'IN'::text"))
    op.drop_index(op.f('uix_attendance_record'), table_name='attendance_logs')
    op.create_unique_constraint('uix_attendance_record', 'attendance_logs', ['tenant_id', 'device_id', 'finger_id', 'timestamp'])
    op.create_index(op.f('ix_attendance_logs_id'), 'attendance_logs', ['id'], unique=False)
    op.alter_column('commands', 'device_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('commands', 'command',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_index(op.f('ix_commands_id'), 'commands', ['id'], unique=False)
    op.alter_column('devices', 'device_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('devices', 'secret_key',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('devices', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('devices_tenant_id_device_id_key'), 'devices', type_='unique')
    op.create_index(op.f('ix_devices_device_id'), 'devices', ['device_id'], unique=False)
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    op.create_index('ix_tenant_device', 'devices', ['tenant_id', 'device_id'], unique=True)
    op.alter_column('tenants', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('tenants', 'api_key',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint(op.f('tenants_api_key_key'), 'tenants', type_='unique')
    op.create_index(op.f('ix_tenants_api_key'), 'tenants', ['api_key'], unique=True)
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.alter_column('users', 'employee_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint(op.f('users_tenant_id_finger_id_key'), 'users', type_='unique')
    op.create_index('ix_tenant_employee_code', 'users', ['tenant_id', 'employee_code'], unique=True)
    op.create_index('ix_tenant_finger', 'users', ['tenant_id', 'finger_id'], unique=True)
    op.create_index(op.f('ix_users_employee_code'), 'users', ['employee_code'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_employee_code'), table_name='users')
    op.drop_index('ix_tenant_finger', table_name='users')
    op.drop_index('ix_tenant_employee_code', table_name='users')
    op.create_unique_constraint(op.f('users_tenant_id_finger_id_key'), 'users', ['tenant_id', 'finger_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'employee_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_api_key'), table_name='tenants')
    op.create_unique_constraint(op.f('tenants_api_key_key'), 'tenants', ['api_key'], postgresql_nulls_not_distinct=False)
    op.alter_column('tenants', 'api_key',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('tenants', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index('ix_tenant_device', table_name='devices')
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_device_id'), table_name='devices')
    op.create_unique_constraint(op.f('devices_tenant_id_device_id_key'), 'devices', ['tenant_id', 'device_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('devices', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('devices', 'secret_key',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('devices', 'device_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_commands_id'), table_name='commands')
    op.alter_column('commands', 'command',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('commands', 'device_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_attendance_logs_id'), table_name='attendance_logs')
    op.drop_constraint('uix_attendance_record', 'attendance_logs', type_='unique')
    op.create_index(op.f('uix_attendance_record'), 'attendance_logs', ['tenant_id', 'device_id', 'finger_id', 'timestamp'], unique=True)
    op.alter_column('attendance_logs', 'record_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'IN'::text"))
    op.alter_column('attendance_logs', 'device_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_admin_users_username'), table_name='admin_users')
    op.drop_index(op.f('ix_admin_users_id'), table_name='admin_users')
    op.drop_index(op.f('ix_admin_users_api_token'), table_name='admin_users')
    op.create_unique_constraint(op.f('admin_users_username_key'), 'admin_users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('admin_users_api_token_key'), 'admin_users', ['api_token'], postgresql_nulls_not_distinct=False)
    op.alter_column('admin_users', 'api_token',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('admin_users', 'password',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('admin_users', 'username',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_table('notifications',
    sa.Column('notification_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('notifications_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('notification_id', name=op.f('notifications_pkey'))
    )
    op.create_table('departments',
    sa.Column('department_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('department_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('departments_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('department_id', name=op.f('departments_pkey'))
    )
    op.create_table('holidays',
    sa.Column('holiday_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('holiday_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('holidays_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('holiday_id', name=op.f('holidays_pkey'))
    )
    op.create_table('leaves',
    sa.Column('leave_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('leave_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'pending'::text"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], name=op.f('leaves_employee_id_fkey')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('leaves_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('leave_id', name=op.f('leaves_pkey'))
    )
    op.create_table('settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('office_start_time', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('office_end_time', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('late_threshold_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('settings_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('settings_pkey')),
    sa.UniqueConstraint('tenant_id', name=op.f('settings_tenant_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('employees',
    sa.Column('employee_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('finger_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], name=op.f('employees_department_id_fkey')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('employees_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('employee_id', name=op.f('employees_pkey'))
    )
    # ### end Alembic commands ###
