"""add record_type to attendance_logs

Revision ID: 90405d9757e0
Revises: 1df3125452f9
Create Date: 2026-04-13 01:57:16.045997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90405d9757e0'
down_revision: Union[str, Sequence[str], None] = '1df3125452f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Added server_default='IN' to populate existing database rows
    op.add_column('attendance_logs', sa.Column('record_type', sa.String(), server_default='IN', nullable=False))
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance_logs', 'record_type')
    # ### end Alembic commands ###
